---
title: "ncc integration"
output: html_document
---

```{r}
library(tidyverse)
library(Seurat)
library(future)
library(SeuratWrappers)
```

```{r}
options(future.globals.maxSize = 18000 * 1024^2)
resPath = "/storage/holab/linxy/vivian/seuratObj/"
#plan("multiprocess", workers = 8)
#plan()
```

## load and merge raw 10X datasets

```{r}
sampleV1 = c('ncc1', 'ncc2', 'ncc3', 'ncc4')
dataL = list()

for (sample in sampleV1) {
  file_name = str_c('/storage/holab/linxy/vivian/', sample, '_cellranger/outs/filtered_feature_bc_matrix')
  print(file_name)
  seuratObj_counts <- Read10X(data.dir = file_name)
  seuratObj = CreateSeuratObject(counts = seuratObj_counts, project = sample)
  dataL[[sample]] <- seuratObj
}

merged_ncc <- merge(dataL[[1]], y = dataL[-1], add.cell.ids = names(dataL), project = "ncc")

# save data
save(merged_ncc, file = str_c(resPath, 'merged_ncc.rdata'))
```

```{r}
load(str_c(resPath, 'merged_ncc.rdata'))
merged_ncc[["percent.mt"]] <- PercentageFeatureSet(object = merged_ncc, pattern = "^MT-")
# Visualize QC metrics as a violin plot
VlnPlot(object =merged_ncc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
#ggsave("./plots/beforeFiltering1.png", width = 16, height = 8)
plot1 <- FeatureScatter(object = merged_ncc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(object = merged_ncc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
#ggsave("./plots/beforeFiltering2.png", width = 16, height = 8)

# filter the low quality cells
ncc <- subset(x = merged_ncc, subset = (nFeature_RNA > 200) & (nFeature_RNA < 1000) & (percent.mt < 10))
# Visualize QC metrics as a violin plot after filtering
VlnPlot(object = ncc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
#ggsave("./plots/afterFiltering1.png", width = 16, height = 8)
plot1 <- FeatureScatter(object = ncc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(object = ncc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
CombinePlots(plots = list(plot1, plot2))
#ggsave("./plots/afterFiltering2.png", width = 16, height = 8)

# save data
save(ncc, file = str_c(resPath, 'filtered_ncc.rdata'))
```


## Check batch effect before integration

No batch effect

```{r, eval = FALSE}
load(str_c(resPath, 'filtered_ncc.rdata'))
ncc <- NormalizeData(ncc)
ncc <- ScaleData(ncc, verbose = FALSE)
ncc <- FindVariableFeatures(ncc, verbose = FALSE)
ncc <- RunPCA(ncc, npcs = 15, verbose = FALSE)
ncc <- RunUMAP(ncc, reduction = "pca", dims = 1:15)
ncc <- FindNeighbors(ncc, reduction = "pca", dims = 1:15)
ncc <- FindClusters(ncc, resolution = 0.5)
# Visualization
p1 <- DimPlot(ncc, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(ncc, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
#ggsave("./plots/UMAP_wbatch.png", width = 16, height = 8)

# save data
save(ncc, file = str_c(resPath, 'clustered_ncc.rdata'))
```

## Find markers

```{r}
ncc.markers <- FindAllMarkers(ncc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
ncc.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10
DoHeatmap(ncc, features = top10$gene) + NoLegend()
ggsave(str_c(resPath, "ncc_markers_heatmap.png"), width = 16, height = 10)
top10 %>% 
  select(cluster, gene) %>% 
  write_csv(str_c(resPath, "ncc_markers.csv"))
```

